// TIRO LIBRE MATEMÁTICO — Level Data V9
// Progresión pedagógica: tablas → coordenadas → física → integración
// =============================================================

import type { LevelConfig, WorldConfig, WorldId } from "../engine/types";

export const WORLDS: WorldConfig[] = [
  {
    id: "tables",
    name: "Academia de tablas",
    icon: "✖️",
    description: "Construye tu precisión con las tablas de multiplicar.",
    objective: "Resolver tablas del 2 al 9 para ganar precisión en el tiro.",
    levelIds: [1, 2],
  },
  {
    id: "goal-map",
    name: "Mapa del gol",
    icon: "📍",
    description: "Convierte coordenadas en zonas claras de la portería.",
    objective: "Leer coordenadas positivas y moverte por el plano cartesiano.",
    levelIds: [3, 4],
  },
  {
    id: "ball-lab",
    name: "Laboratorio del balón",
    icon: "🌀",
    description: "Descubre cómo los cálculos cambian la trayectoria.",
    objective: "Relacionar ángulos, trayectorias, velocidad y distancia.",
    levelIds: [5, 6, 7],
  },
  {
    id: "stem-cup",
    name: "Copa STEM",
    icon: "🏆",
    description: "El partido final reúne todo lo que aprendiste.",
    objective: "Integrar los cuatro conceptos en una competencia justa y legible.",
    levelIds: [8],
  },
];

const WORLD_BY_ID = new Map<WorldId, WorldConfig>(WORLDS.map((world) => [world.id, world]));

interface LevelDefinition extends Omit<LevelConfig, "worldName" | "worldIcon" | "worldDescription" | "learningObjective"> {
  worldId: WorldId;
}

function withWorld(level: LevelDefinition): LevelConfig {
  const world = WORLD_BY_ID.get(level.worldId);
  if (!world) throw new Error(`Unknown world: ${level.worldId}`);
  return {
    ...level,
    worldName: world.name,
    worldIcon: world.icon,
    worldDescription: world.description,
    learningObjective: world.objective,
  };
}

export const LEVELS: LevelConfig[] = [
  withWorld({
    id: 1,
    worldId: "tables",
    name: "Tablas 2–5",
    concept: "directions",
    description: "Aprende a apuntar y resuelve tablas pequeñas para convertir cada acierto en precisión.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: false,
    keeperSpeed: 0,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "easy",
    tableRange: { min: 2, max: 5 },
    challengeTypes: ["multiplication"],
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Siempre disponible",
    rewards: { xp: 50, coins: 20, unlocks: ["level_2"] },
  }),
  withWorld({
    id: 2,
    worldId: "tables",
    name: "Tablas 6–9",
    concept: "multiplication",
    description: "Sube el reto con las tablas del 6 al 9 y conserva tu precisión.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.22,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "medium",
    tableRange: { min: 6, max: 9 },
    challengeTypes: ["multiplication"],
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 1",
    rewards: { xp: 75, coins: 30, unlocks: ["level_3"] },
  }),
  withWorld({
    id: 3,
    worldId: "goal-map",
    name: "Coordenadas positivas",
    concept: "coordinates",
    description: "Lee puntos positivos y elige con precisión tu zona de gol.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.3,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "easy",
    challengeTypes: ["coordinate"],
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 2",
    rewards: { xp: 100, coins: 40, unlocks: ["level_4", "ball_fire"] },
  }),
  withWorld({
    id: 4,
    worldId: "goal-map",
    name: "Plano cartesiano",
    concept: "cartesian",
    description: "Usa los cuatro cuadrantes para encontrar el destino correcto.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.4,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    challengeTypes: ["coordinate"],
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 3",
    rewards: { xp: 150, coins: 60, unlocks: ["level_5"] },
  }),
  withWorld({
    id: 5,
    worldId: "ball-lab",
    name: "Ángulos y barrera",
    concept: "angles",
    description: "Calcula el ángulo útil para superar la barrera.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.45,
    hasWall: true,
    wallCount: 3,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    challengeTypes: ["angle"],
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 4",
    rewards: { xp: 200, coins: 80, unlocks: ["level_6", "kit_champion"] },
  }),
  withWorld({
    id: 6,
    worldId: "ball-lab",
    name: "Trayectorias curvas",
    concept: "trajectories",
    description: "Relaciona el efecto con la curva que dibuja el balón.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.52,
    hasWall: true,
    wallCount: 3,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    challengeTypes: ["angle"],
    timeBonus: true,
    wind: false,
    windStrength: 0,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 5",
    rewards: { xp: 250, coins: 100, unlocks: ["level_7"] },
  }),
  withWorld({
    id: 7,
    worldId: "ball-lab",
    name: "Velocidad y distancia",
    concept: "velocity",
    description: "Calcula cuánto viaja el balón con velocidad y tiempo.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.6,
    hasWall: true,
    wallCount: 4,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "hard",
    challengeTypes: ["velocity"],
    timeBonus: true,
    wind: true,
    windStrength: 0.25,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 6",
    rewards: { xp: 300, coins: 120, unlocks: ["level_8", "ball_golden"] },
  }),
  withWorld({
    id: 8,
    worldId: "stem-cup",
    name: "Copa STEM",
    concept: "tactics",
    description: "Integra tablas, coordenadas, ángulos y velocidad en la final.",
    shotsRequired: 5,
    shotsAllowed: 7,
    hasKeeper: true,
    keeperSpeed: 0.62,
    hasWall: true,
    wallCount: 4,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "hard",
    challengeTypes: ["multiplication", "coordinate", "angle", "velocity"],
    timeBonus: true,
    wind: true,
    windStrength: 0.28,
    stars: [7, 6, 5],
    unlockCondition: "Completa Nivel 7",
    rewards: { xp: 500, coins: 200, unlocks: ["trophy_math_cup"] },
  }),
];

export const getLevelById = (id: number): LevelConfig | undefined =>
  LEVELS.find((level) => level.id === id);

export const getWorldById = (id: WorldId): WorldConfig | undefined => WORLD_BY_ID.get(id);

export const CONCEPT_LABELS: Record<string, string> = {
  directions: "Direcciones",
  coordinates: "Coordenadas",
  multiplication: "Multiplicación",
  cartesian: "Plano cartesiano",
  angles: "Ángulos",
  trajectories: "Trayectorias",
  velocity: "Velocidad",
  tactics: "Tácticas",
};

export const CONCEPT_ICONS: Record<string, string> = {
  directions: "🧭",
  coordinates: "📍",
  multiplication: "✖️",
  cartesian: "📐",
  angles: "📏",
  trajectories: "🌀",
  velocity: "⚡",
  tactics: "🏆",
};
