// =============================================================
// TIRO LIBRE MATEMÁTICO — Level Data
// 8 niveles de progresión matemática STEM
// =============================================================

import type { LevelConfig } from "../engine/types";

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: "Entrenamiento",
    concept: "directions",
    description: "Aprende a apuntar. ¡Mete el balón en la portería!",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: false,
    keeperSpeed: 0,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "easy",
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Siempre disponible",
    rewards: { xp: 50, coins: 20, unlocks: ["level_2"] },
  },
  {
    id: 2,
    name: "El Portero",
    concept: "coordinates",
    description: "¡Hay portero! Usa coordenadas para apuntar lejos de él.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.3,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "easy",
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 1",
    rewards: { xp: 75, coins: 30, unlocks: ["level_3"] },
  },
  {
    id: 3,
    name: "Multiplicación Power",
    concept: "multiplication",
    description: "¡Resuelve multiplicaciones para dar más potencia a tu tiro!",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.4,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 1,
    mathDifficulty: "easy",
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 2",
    rewards: { xp: 100, coins: 40, unlocks: ["level_4", "ball_fire"] },
  },
  {
    id: 4,
    name: "Plano Cartesiano",
    concept: "cartesian",
    description: "¡Los 4 cuadrantes! Coordenadas positivas Y negativas.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.5,
    hasWall: false,
    wallCount: 0,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 3",
    rewards: { xp: 150, coins: 60, unlocks: ["level_5"] },
  },
  {
    id: 5,
    name: "La Barrera",
    concept: "angles",
    description: "¡Hay barrera! Calcula el ángulo para esquivarla.",
    shotsRequired: 3,
    shotsAllowed: 5,
    hasKeeper: true,
    keeperSpeed: 0.5,
    hasWall: true,
    wallCount: 3,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    timeBonus: false,
    wind: false,
    windStrength: 0,
    stars: [5, 4, 3],
    unlockCondition: "Completa Nivel 4",
    rewards: { xp: 200, coins: 80, unlocks: ["level_6", "kit_champion"] },
  },
  {
    id: 6,
    name: "Trayectorias",
    concept: "trajectories",
    description: "Controla la curva del balón con el efecto correcto.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.6,
    hasWall: true,
    wallCount: 4,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "medium",
    timeBonus: true,
    wind: false,
    windStrength: 0,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 5",
    rewards: { xp: 250, coins: 100, unlocks: ["level_7"] },
  },
  {
    id: 7,
    name: "Velocidad y Fuerza",
    concept: "velocity",
    description: "¡Viento en contra! Calcula la velocidad exacta.",
    shotsRequired: 4,
    shotsAllowed: 6,
    hasKeeper: true,
    keeperSpeed: 0.7,
    hasWall: true,
    wallCount: 4,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "hard",
    timeBonus: true,
    wind: true,
    windStrength: 0.3,
    stars: [6, 5, 4],
    unlockCondition: "Completa Nivel 6",
    rewards: { xp: 300, coins: 120, unlocks: ["level_8", "ball_golden"] },
  },
  {
    id: 8,
    name: "Copa Matemática",
    concept: "tactics",
    description: "¡El partido final! Usa todo lo que aprendiste.",
    shotsRequired: 5,
    shotsAllowed: 7,
    hasKeeper: true,
    keeperSpeed: 0.8,
    hasWall: true,
    wallCount: 5,
    gridVisible: true,
    gridQuadrants: 4,
    mathDifficulty: "hard",
    timeBonus: true,
    wind: true,
    windStrength: 0.4,
    stars: [7, 6, 5],
    unlockCondition: "Completa Nivel 7",
    rewards: { xp: 500, coins: 200, unlocks: ["trophy_math_cup"] },
  },
];

export const getLevelById = (id: number): LevelConfig | undefined =>
  LEVELS.find((l) => l.id === id);

export const CONCEPT_LABELS: Record<string, string> = {
  directions: "Direcciones",
  coordinates: "Coordenadas",
  multiplication: "Multiplicación",
  cartesian: "Plano Cartesiano",
  angles: "Ángulos",
  trajectories: "Trayectorias",
  velocity: "Velocidad",
  tactics: "Tácticas",
};

export const CONCEPT_ICONS: Record<string, string> = {
  directions: "🧭",
  coordinates: "📍",
  multiplication: "✖️",
  cartesian: "📐",
  angles: "📏",
  trajectories: "🌀",
  velocity: "⚡",
  tactics: "🏆",
};
