'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const leagues=[{name:'La cantera',stadium:'CANCHA DE BARRIO',min:2,max:5,xp:0,desc:'Tablas del 2 al 5 · Divisiones exactas'},{name:'Liga ascenso',stadium:'ARENA METROPOLITANA',min:3,max:9,xp:180,desc:'Tablas del 3 al 9 · Nuevos desafíos'},{name:'Noche de final',stadium:'ESTADIO DE CAMPEONES',min:6,max:12,xp:420,desc:'Tablas del 6 al 12 · Dominio total'}];
let saved={xp:0,best:0};try{const d=JSON.parse(localStorage.getItem('gol-lab-v1'));if(d&&Number.isFinite(d.xp)&&d.xp>=0)saved={xp:Math.floor(d.xp),best:Math.min(5,Math.max(0,Number(d.best)||0))}}catch{}
let league=0,mode='multiply',phase='question',q,shots=[],goals=0,streak=0,firstTry=true,helped=false,ball=null,keeperX=550,keeperEnd=550,animStart=0,target={x:720,y:240},sound=false,ac,matchXp=0,review=[],retryQuestion=null;
function persist(){try{localStorage.setItem('gol-lab-v1',JSON.stringify(saved))}catch{$('progressText').textContent='El navegador no permite guardar; el progreso durará esta sesión.'}}
function addXp(n){saved.xp+=n;matchXp+=n;persist();renderStats()}
function renderStats(){ $('xp').textContent=saved.xp+' XP';$('rank').textContent='Nivel '+(1+Math.floor(saved.xp/100))+' · '+(saved.xp>=420?'Campeón':saved.xp>=180?'Ascenso':'Cantera');$('best').textContent='Récord: '+saved.best+' goles';$('goals').textContent=goals;$('streak').textContent='Racha de cálculo: '+streak;$('shotLabel').textContent=phase==='end'?'PARTIDO TERMINADO':'TIRO '+Math.min(5,shots.length+1)+' DE 5';$('dots').innerHTML=Array.from({length:5},(_,i)=>'<i class="'+(i<shots.length?(shots[i]?'goal':'miss'):(i===shots.length?'current':''))+'"></i>').join('');$('leagues').innerHTML=leagues.map((l,i)=>'<button class="league '+(i===league?'active':'')+'" data-league="'+i+'" '+(saved.xp<l.xp||phase==='flight'?'disabled':'')+'><small>'+(saved.xp<l.xp?'BLOQUEADA · '+l.xp+' XP':i===league?'ESTÁS JUGANDO AQUÍ':'DISPONIBLE')+'</small><span class="num">0'+(i+1)+'</span><b>'+l.name+'</b><p>'+l.desc+'</p></button>').join('');document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.league)===league)return;league=Number(b.dataset.league);resetMatch()});const next=leagues.find(l=>saved.xp<l.xp);$('progressText').textContent=next?(next.xp-saved.xp)+' XP para desbloquear '+next.name:'Todas las ligas desbloqueadas. ¡A mejorar tu récord!'}
function setPhase(p){phase=p;$('questionPanel').hidden=p!=='question';$('aimPanel').hidden=p!=='aim';$('resultPanel').hidden=!['result','end'].includes(p);$('stepNo').textContent=p==='question'?'01':p==='aim'?'02':'03';$('stepSmall').textContent=p==='question'?'PIENSA LA JUGADA':p==='aim'?'ELIGE TU DISPARO':'REVISA TU JUGADA';$('stepTitle').textContent=p==='question'?'Resuelve y prepara el tiro':p==='aim'?'Busca la escuadra':p==='end'?'Partido terminado':'Una jugada más';$('phaseTag').textContent=p==='question'?'PREPARA LA JUGADA':p==='aim'?'APUNTA Y DISPARA':p==='flight'?'BALÓN EN JUEGO':p==='end'?'FINAL DEL PARTIDO':'REPASA Y SIGUE';renderStats()}
function randint(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function newQuestion(){setPhase('question');firstTry=true;helped=false;ball=null;keeperX=550;$('celebration').textContent='';$('feedback').textContent='';const l=leagues[league],a=randint(l.min,l.max),b=randint(2,12),division=mode==='divide'||(mode==='mixed'&&Math.random()<.5);q=retryQuestion||{a,b,division};retryQuestion=null;const answer=q.division?q.b:q.a*q.b;q.answer=answer;$('equation').textContent=q.division?q.a*q.b+' ÷ '+q.a+' = ?':q.a+' × '+q.b+' = ?';let options=new Set([answer]);while(options.size<4){const candidate=answer+randint(-Math.max(4,q.a*2),Math.max(4,q.a*2));if(candidate>0)options.add(candidate)}$('answers').innerHTML=[...options].sort(()=>Math.random()-.5).map(n=>'<button data-answer="'+n+'">'+n+'</button>').join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.answer),b));draw()}
function hint(){helped=true;$('feedback').textContent=q.division?'Piensa al revés: '+q.a+' × ¿qué número? = '+q.a*q.b+'. Reparte '+q.a*q.b+' en '+q.a+' grupos iguales.':q.b>5?'Descompón: '+q.a+' × '+q.b+' = ('+q.a+' × 5) + ('+q.a+' × '+(q.b-5)+').':'Suma '+q.a+' un total de '+q.b+' veces: '+Array(q.b).fill(q.a).join(' + ')+'.'}
function answerQuestion(n,button){if(phase!=='question')return;if(n!==q.answer){firstTry=false;streak=0;button.disabled=true;hint();$('feedback').textContent='Casi. '+$('feedback').textContent;review.push({...q});renderStats();tone(180,.1);return}streak=firstTry&&!helped?streak+1:0;const xp=firstTry&&!helped?20:10;addXp(xp);$('feedback').textContent='¡Correcto! '+(q.division?q.a*q.b+' ÷ '+q.a+' = '+q.b:q.a+' × '+q.b+' = '+q.answer)+'. +'+xp+' XP'+(streak>=3?' · ¡Racha encendida!':'');setPhase('aim');tone(580,.12);draw()}
function resetMatch(){shots=[];goals=0;streak=0;matchXp=0;retryQuestion=review.shift()||null;$('stadium').textContent='0'+(league+1)+' / '+leagues[league].stadium;$('leagueTitle').textContent=leagues[league].name;newQuestion()}
function shotOutcome(x,y,p){const actualY=y+(p<60?(60-p)*4:p>85?-(p-85)*4:0);if(actualY<192||actualY>376||x<280||x>820)return{goal:false,x,y:actualY,reason:p<60?'La potencia se quedó corta. Prueba entre 60% y 85%.':'El balón salió por encima. Baja la potencia o apunta más abajo.'};if(x>420&&x<545&&actualY>270)return{goal:false,x,y:actualY,wall:true,reason:'La barrera bloqueó el tiro. Busca un lateral o eleva la trayectoria.'};if(Math.abs(x-550)<110&&actualY>248)return{goal:false,x,y:actualY,reason:'El portero cubrió el centro. Prueba una esquina.'};return{goal:true,x,y:actualY,reason:'Buena lectura y precisión: encontraste un espacio libre.'}}
function shoot(){if(phase!=='aim')return;const outcome=shotOutcome(target.x,target.y,Number($('power').value));ball={outcome,t:0};keeperEnd=550+Math.max(-80,Math.min(80,(outcome.x-550)*.45));animStart=performance.now();setPhase('flight');$('feedback').textContent='';tone(120,.1);requestAnimationFrame(animate)}
function animate(now){if(phase!=='flight')return;ball.t=Math.min(1,(now-animStart)/1050);keeperX=550+(keeperEnd-550)*ball.t;draw();if(ball.t<1)requestAnimationFrame(animate);else finishShot()}
function finishShot(){const o=ball.outcome;shots.push(o.goal);if(o.goal){goals++;addXp(15);tone(780,.2)}else tone(160,.2);$('celebration').textContent=o.goal?'¡GOLAZO!':o.wall?'BARRERA':o.y<192||o.y>376?'FUERA':'¡ATAJADA!';setPhase('result');$('resultTitle').textContent=o.goal?'Así se define.':'Ajusta el siguiente tiro.';$('resultText').textContent=o.reason+(o.goal?' +15 XP por el gol.':'');$('next').textContent=shots.length===5?'VER RESULTADO →':'SIGUIENTE TIRO →'}
function next(){if(phase==='end'){resetMatch();return}if(phase!=='result')return;if(shots.length===5){if(goals>=3)addXp(60);saved.best=Math.max(saved.best,goals);persist();setPhase('end');$('resultTitle').textContent=goals>=3?'¡Objetivo cumplido!':'Buen entrenamiento.';$('resultText').textContent=goals+' goles de 5 · +'+matchXp+' XP. '+(review.length?'Seguiremos repasando las operaciones que costaron más.':'¡Gran trabajo de cálculo!')+(goals>=3?' Ganaste el bonus de 60 XP.':' Vuelve por los 3 goles.');$('next').textContent='JUGAR OTRO PARTIDO →';$('celebration').textContent=goals>=3?'MISIÓN CUMPLIDA':'SIGUE ENTRENANDO';return}if(review.length&&Math.random()<.7)retryQuestion=review.shift();newQuestion()}
function tone(f,d){if(!sound)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=f;g.gain.setValueAtTime(.055,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.start();o.stop(ac.currentTime+d)}catch{}}
function line(x1,y1,x2,y2,color='#d8ebd6',width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill()}
function person(x,y,scale,shirt,keeper=false){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#001d2080';ctx.beginPath();ctx.ellipse(0,4,23,7,0,0,Math.PI*2);ctx.fill();line(-7,-22,-12,0,'#14252c',9);line(7,-22,13,0,'#14252c',9);line(-13,0,-20,0,'#f2ffac',5);line(13,0,20,0,'#f2ffac',5);poly([[-14,-57],[14,-57],[12,-22],[-12,-22]],shirt);line(-12,-50,keeper?-37:-20,keeper?-47:-29,shirt,9);line(12,-50,keeper?37:20,keeper?-47:-29,shirt,9);ctx.fillStyle='#bf957d';ctx.beginPath();ctx.arc(0,-69,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#172327';ctx.beginPath();ctx.arc(0,-72,10,Math.PI,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){const w=1100,h=650;ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,250);sky.addColorStop(0,league===2?'#061123':'#133039');sky.addColorStop(1,'#63817b');ctx.fillStyle=sky;ctx.fillRect(0,0,w,280);
// The canvas is the interactive game world: pitch, collision surfaces and actors.
poly([[0,135],[160,90],[940,90],[1100,135],[1100,300],[0,300]],'#172c32');for(let row=0;row<8;row++){line(0,145+row*16,1100,145+row*16,'#406267',2);for(let col=0;col<68;col++){ctx.fillStyle=['#6d8987','#98a9a0','#2a4a4b','#b9c09e'][(row*17+col*7)%4];ctx.fillRect(col*17+row%2*8,140+row*16,4,5)}}line(0,132,160,88,'#96b0ab',3);line(160,88,940,88,'#96b0ab',3);line(940,88,1100,132,'#96b0ab',3);for(const x of [95,1005]){line(x,35,x,270,'#577a78',5);ctx.fillStyle='#edffd5';ctx.fillRect(x-33,32,66,9);const glow=ctx.createRadialGradient(x,38,2,x,38,110);glow.addColorStop(0,'#e5ffc947');glow.addColorStop(1,'#e5ffc900');ctx.fillStyle=glow;ctx.fillRect(x-110,0,220,150)}
const grass=ctx.createLinearGradient(0,260,0,650);grass.addColorStop(0,'#4b7851');grass.addColorStop(1,'#173d2d');ctx.fillStyle=grass;ctx.fillRect(0,270,w,380);for(let i=0;i<8;i++){const a=270+Math.pow(i/8,1.6)*380,b=270+Math.pow((i+1)/8,1.6)*380;ctx.fillStyle=i%2?'#b0cc7020':'#082f1919';ctx.fillRect(0,a,w,b-a)}line(0,377,1100,377,'#d7e6c285',2);line(240,377,40,650,'#d7e6c285',3);line(860,377,1060,650,'#d7e6c285',3);line(125,529,975,529,'#d7e6c285',3);line(337,377,287,452,'#d7e6c285',2);line(763,377,813,452,'#d7e6c285',2);line(287,452,813,452,'#d7e6c285',2);ctx.strokeStyle='#d7e6c270';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(550,529,150,48,0,0,Math.PI);ctx.stroke();
poly([[280,192],[310,211],[790,211],[820,192]],'#d4e4d016');poly([[280,192],[820,192],[820,376],[280,376]],'#071c3038');for(let x=280;x<=820;x+=20)line(x,192,x,376,'#e4f2ef48',1);for(let y=192;y<=376;y+=15)line(280,y,820,y,'#e4f2ef48',1);line(280,376,280,192,'#edf8ef',7);line(280,192,820,192,'#edf8ef',7);line(820,192,820,376,'#edf8ef',7);line(280,376,820,376,'#efffe533',2);
person(keeperX,369,1.18,'#ffae4e',true);for(const x of [447,485,523])person(x,447,1.04,'#a9cddd');
if(phase==='aim'){ctx.setLineDash([6,12]);ctx.beginPath();ctx.moveTo(550,584);ctx.quadraticCurveTo(target.x,350,target.x,target.y);ctx.strokeStyle='#d8ff6970';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#d6ff4b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(target.x,target.y,18,0,Math.PI*2);ctx.stroke();line(target.x-28,target.y,target.x-9,target.y,'#d6ff4b',2);line(target.x+9,target.y,target.x+28,target.y,'#d6ff4b',2);line(target.x,target.y-28,target.x,target.y-9,'#d6ff4b',2);line(target.x,target.y+9,target.x,target.y+28,'#d6ff4b',2)}
let bx=550,by=584,br=14;if(ball){const t=ball.t;bx=550+(ball.outcome.x-550)*t;by=584+(ball.outcome.y-584)*t-90*Math.sin(Math.PI*t);br=14-7*t}ctx.fillStyle='#00191670';ctx.beginPath();ctx.ellipse(bx,ball?584+(376-584)*ball.t:600,br*1.3,4,0,0,Math.PI*2);ctx.fill();const bg=ctx.createRadialGradient(bx-br/3,by-br/3,1,bx,by,br);bg.addColorStop(0,'#ffffff');bg.addColorStop(1,'#95aeb4');ctx.fillStyle=bg;ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.fill();poly(Array.from({length:5},(_,i)=>[bx+Math.cos(i*Math.PI*2/5)*br*.46,by+Math.sin(i*Math.PI*2/5)*br*.46]),'#192d38');if(phase!=='flight')person(495,622,1.55,'#cfff42');}
$('hint').onclick=hint;$('shoot').onclick=shoot;$('next').onclick=next;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='Sonido: '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));tone(500,.1)};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(phase!=='question'||mode===b.dataset.mode)return;mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));retryQuestion=null;newQuestion()});function syncAim(){target={x:Number($('aimX').value),y:Number($('aimY').value)};$('aimValue').textContent=target.x<490?'Izquierda':target.x>610?'Derecha':'Centro';$('powerValue').textContent=$('power').value+'%';draw()}['aimX','aimY','power'].forEach(id=>$(id).oninput=syncAim);canvas.addEventListener('pointerdown',e=>{if(phase!=='aim')return;const r=canvas.getBoundingClientRect();$('aimX').value=Math.max(285,Math.min(815,(e.clientX-r.left)/r.width*1100));$('aimY').value=Math.max(200,Math.min(370,(e.clientY-r.top)/r.height*650));syncAim()});canvas.addEventListener('keydown',e=>{if(phase!=='aim')return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')$('aimX').value=target.x-15;if(e.key==='ArrowRight')$('aimX').value=target.x+15;if(e.key==='ArrowUp')$('aimY').value=target.y-10;if(e.key==='ArrowDown')$('aimY').value=target.y+10;if(e.key===' ')shoot();syncAim()});resetMatch();
